site_name: fiware-cygnus
site_url: https://fiware-cygnus.readthedocs.org
repo_url: https://github.com/telefonicaid/fiware-cygnus
site_description: Cygnus Documentation
docs_dir: doc
site_dir: html
edit_uri: edit/master/doc/
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css", "https://fiware.org/style/fiware_readthedocs_core.css"]
google_analytics: ['UA-84866051-2', 'fiware-cygnus.readthedocs.io']
pages:
  - Home: index.md
  - 'Architecture': architecture.md
  - 'cygnus-common library':
      - 'Installation and Administration Guide':
          - 'Introduction': 'cygnus-common/installation_and_administration_guide/introduction.md'
          - 'Hardware requirements': 'cygnus-common/installation_and_administration_guide/hw_requirements.md'
          - 'Installation via RPM': 'cygnus-common/installation_and_administration_guide/install_with_rpm.md'
          - 'Installation from sources': 'cygnus-common/installation_and_administration_guide/install_from_sources.md'
          - 'Installation via docker': 'cygnus-common/installation_and_administration_guide/install_with_docker.md'
          - 'Cygnus agent configuration': 'cygnus-common/installation_and_administration_guide/cygnus_agent_conf.md'
          - 'Flume environment configuration': 'cygnus-common/installation_and_administration_guide/flume_env_conf.md'
          - 'log4j configuration': 'cygnus-common/installation_and_administration_guide/log4j_conf.md'
          - 'Running as a process': 'cygnus-common/installation_and_administration_guide/running_as_process.md'
          - 'YAFS': 'cygnus-common/installation_and_administration_guide/yafs.md'
          - 'Testing': 'cygnus-common/installation_and_administration_guide/testing.md'
          - 'Logs and alarms': 'cygnus-common/installation_and_administration_guide/logs_and_alarms.md'
          - 'Original API': 'cygnus-common/installation_and_administration_guide/management_interface.md'
          - 'v1 API (beta)' : 'cygnus-common/installation_and_administration_guide/management_interface_v1.md'
          - 'Sanity checks': 'cygnus-common/installation_and_administration_guide/sanity_checks.md'
          - 'Diagnosis procedures': 'cygnus-common/installation_and_administration_guide/diagnosis_procedures.md'
          - 'Reporting issues and contact information': 'cygnus-common/installation_and_administration_guide/issues_and_contact.md'
      - 'Backends catalogue':
          - 'Introduction': 'cygnus-common/backends_catalogue/introduction.md'
          - 'CKAN backend': 'cygnus-common/backends_catalogue/ckan_backend.md'
          - 'DynamoDB backend': 'cygnus-common/backends_catalogue/dynamodb_backend.md'
          - 'HDFS backend': 'cygnus-common/backends_catalogue/hdfs_backend.md'
          - 'Hive backend': 'cygnus-common/backends_catalogue/hive_backend.md'
          - 'Http backend': 'cygnus-common/backends_catalogue/http_backend.md'
          - 'Kafka backend': 'cygnus-common/backends_catalogue/kafka_backend.md'
          - 'MongoDB backend': 'cygnus-common/backends_catalogue/mongodb_backend.md'
          - 'MySQL backend': 'cygnus-common/backends_catalogue/mysql_backend.md'
          - 'Orion backend': 'cygnus-common/backends_catalogue/orion_backend.md'
          - 'PostgreSQL backend': 'cygnus-common/backends_catalogue/postgresql_backend.md'
          - 'CartoDB backend': 'cygnus-common/backends_catalogue/cartodb_backend.md'
          - 'Elasticsearch backend': 'cygnus-common/backends_catalogue/elasticsearch_backend.md'
  - 'cygnus-ngsi agent':
      - 'Quick Start Guide': 'cygnus-ngsi/quick_start_guide.md'
      - 'Installation and Administration Guide':
          - 'Introduction': 'cygnus-ngsi/installation_and_administration_guide/introduction.md'
          - 'Installation via RPM': 'cygnus-ngsi/installation_and_administration_guide/install_with_rpm.md'
          - 'Installation via docker': 'cygnus-ngsi/installation_and_administration_guide/install_with_docker.md'
          - 'Installation from sources': 'cygnus-ngsi/installation_and_administration_guide/install_from_sources.md'
          - 'NGSI agent configuration': 'cygnus-ngsi/installation_and_administration_guide/ngsi_agent_conf.md'
          - 'Configuration examples': 'cygnus-ngsi/installation_and_administration_guide/configuration_examples.md'
          - 'Running as a service': 'cygnus-ngsi/installation_and_administration_guide/running_as_service.md'
          - 'Testing': 'cygnus-ngsi/installation_and_administration_guide/testing.md'
          - 'Backends as short-term historics': 'cygnus-ngsi/installation_and_administration_guide/backends_as_sth.md'
          - 'Name mappings': 'cygnus-ngsi/installation_and_administration_guide/name_mappings.md'
          - 'Grouping Rules': 'cygnus-ngsi/installation_and_administration_guide/grouping_rules.md'
          - 'Multitenancy': 'cygnus-ngsi/installation_and_administration_guide/multitenancy.md'
          - 'Reliability': 'cygnus-ngsi/installation_and_administration_guide/reliability.md'
          - 'Performance tips': 'cygnus-ngsi/installation_and_administration_guide/performance_tips.md'
          - 'NGSIv2 support': 'cygnus-ngsi/installation_and_administration_guide/ngsiv2_support.md'
          - 'IPv6 support': 'cygnus-ngsi/installation_and_administration_guide/ipv6_support.md'
          - 'Deprecated and removed functionality': 'cygnus-ngsi/installation_and_administration_guide/deprecated_and_removed.md'
          - 'Sanity checks': 'cygnus-ngsi/installation_and_administration_guide/sanity_checks.md'
          - 'Diagnosis procedures': 'cygnus-ngsi/installation_and_administration_guide/diagnosis_procedures.md'
          - 'Reporting issues and contact information': 'cygnus-ngsi/installation_and_administration_guide/issues_and_contact.md'
      - 'User and Programmer Guide':
          - 'Introduction': 'cygnus-ngsi/user_and_programmer_guide/introduction.md'
          - 'Connecting Orion Context Broker and Cygnus': 'cygnus-ngsi/user_and_programmer_guide/connecting_orion.md'
          - 'Adding a new sink': 'cygnus-ngsi/user_and_programmer_guide/adding_new_sink.md'
          - 'Reporting issues and contact information': 'cygnus-ngsi/user_and_programmer_guide/issues_and_contact.md'
      - 'Flume extensions catalogue':
          - 'Introduction': 'cygnus-ngsi/flume_extensions_catalogue/introduction.md'
          - 'NGSIRestHandler': 'cygnus-ngsi/flume_extensions_catalogue/ngsi_rest_handler.md'
          - 'NGSICartoDBSink': 'cygnus-ngsi/flume_extensions_catalogue/ngsi_cartodb_sink.md'
          - 'NGSICKANSink': 'cygnus-ngsi/flume_extensions_catalogue/ngsi_ckan_sink.md'
          - 'NGSIDynamoDBSink': 'cygnus-ngsi/flume_extensions_catalogue/ngsi_dynamodb_sink.md'
          - 'NGSIKafkaSink': 'cygnus-ngsi/flume_extensions_catalogue/ngsi_kafka_sink.md'
          - 'NGSIHDFSSink': 'cygnus-ngsi/flume_extensions_catalogue/ngsi_hdfs_sink.md'
          - 'NGSIMongoSink': 'cygnus-ngsi/flume_extensions_catalogue/ngsi_mongo_sink.md'
          - 'NGSIMySQLSink': 'cygnus-ngsi/flume_extensions_catalogue/ngsi_mysql_sink.md'
          - 'NGSIPostgreSQLSink': 'cygnus-ngsi/flume_extensions_catalogue/ngsi_postgresql_sink.md'
          - 'NGSIPostGISSink': 'cygnus-ngsi/flume_extensions_catalogue/ngsi_postgis_sink.md'
          - 'NGSISTHSink': 'cygnus-ngsi/flume_extensions_catalogue/ngsi_sth_sink.md'
          - 'NGSIOrionSink': 'cygnus-ngsi/flume_extensions_catalogue/ngsi_orion_sink.md'
          - 'NGSIElasticsearchSink': 'cygnus-ngsi/flume_extensions_catalogue/ngsi_elasticsearch_sink.md'
          - 'NGSITestSink': 'cygnus-ngsi/flume_extensions_catalogue/ngsi_test_sink.md'
          - 'NGSIGroupingInterceptor': 'cygnus-ngsi/flume_extensions_catalogue/ngsi_grouping_interceptor.md'
          - 'NGSINameMappingsInterceptor': 'cygnus-ngsi/flume_extensions_catalogue/ngsi_name_mappings_interceptor.md'
          - 'RoundRobinChannelSelector': 'cygnus-ngsi/flume_extensions_catalogue/round_robin_channel_selector.md'
          - 'Reporting issues and contact information': 'cygnus-ngsi/flume_extensions_catalogue/issues_and_contact.md'
      - 'Integration examples':
          - 'Integration with Apache Spark': 'cygnus-ngsi/integration/orion_cygnus_spark.md'
          - 'Integration with Apache Kafka': 'cygnus-ngsi/integration/orion_cygnus_kafka.md'
  - 'cygnus-twitter agent':
      - 'Installation and Administration Guide':
          - 'Introduction': 'cygnus-twitter/installation_and_administration_guide/introduction.md'
          - 'Installation via docker': 'cygnus-twitter/installation_and_administration_guide/install_with_docker.md'
          - 'Installation from sources': 'cygnus-twitter/installation_and_administration_guide/install_from_sources.md'
          - 'Twitter agent configuration': 'cygnus-twitter/installation_and_administration_guide/configuration.md'
          - 'Running from cmd': 'cygnus-twitter/installation_and_administration_guide/running.md'
          - 'Testing': 'cygnus-twitter/installation_and_administration_guide/testing.md'
          - 'Logs and alarms': 'cygnus-twitter/installation_and_administration_guide/logs_and_alarms.md'
          - 'Reporting issues and contact information': 'cygnus-twitter/installation_and_administration_guide/issues_and_contact.md'
      - 'User and Programmer Guide':
          - 'Programmer Guide': 'cygnus-twitter/user_and_programmer_guide/programmer_guide.md'
          - 'Reporting issues and contact information': 'cygnus-twitter/user_and_programmer_guide/issues_and_contact.md'
      - 'Flume extensions catalogue':
          - 'Introduction': 'cygnus-twitter/flume_extensions_catalogue/introduction.md'
          - 'TwitterSource': 'cygnus-twitter/flume_extensions_catalogue/twitter_source.md'
          - 'TwitterHDFSink': 'cygnus-twitter/flume_extensions_catalogue/twitter_hdfs_sink.md'
          - 'Reporting issues and contact information': 'cygnus-twitter/flume_extensions_catalogue/issues_and_contact.md'
      - 'Quick Start Guide': 'cygnus-twitter/quick_start_guide.md'
